version: '3'

services:
  account:
    build: ./account
    ports:
      - "8000:8000"
    network_mode: host
    depends_on:
      - account-register

  account-register:
    build: ./account-register
    ports:
      - "8081:8081"
    network_mode: host
