version: '3'

services:
  account:
    build: ./account
    ports:
      - "9090:9090"
    network_mode: host
    depends_on:
      - account-register

  account-register:
    build: ./account-register
    ports:
      - "9091:9091"
    network_mode: host
